//using structuralDesignPatterns.src.Composite;
//using structuralDesignPatterns.src.CompositeWithAbstractComponent;
//using structuralDesignPatterns.src.Adapter;
//using structuralDesignPatterns.src.Bridge;
//using structuralDesignPatterns.src.Proxy.NaiveExample;
//using structuralDesignPatterns.src.Proxy;
//using structuralDesignPatterns.src.Flyweight.NaiveExample;
//using structuralDesignPatterns.src.Flyweight;
//using structuralDesignPatterns.src.Facade;
using structuralDesignPatterns.src.Decorator;

//RunComposite.RunCompositePattern();
//RunCompositeWithAbstractClass.RunCompositeWithAbstractClassPattern();
//RunAdapter.RunAdapterPattern();
//RunBridge.RunBridgePattern();
//RunProxyNaiveExample.RunProxyNaiveExampleCode();
//RunProxy.RunProxyPattern();
//RunFlyweightNaiveExample.RunFlyWeightNaiveExampleCode();
//RunFlyweight.RunFlyWeightPattern();
//RunFacade.RunFacadePattern();
RunDecorator.RunDecoratorPattern();
